# Verifique o tipo de dados de todas as suas variáveis ​​usando a função interna type()

print(type("oi"))
print(type(True))
print(type(10))
print(type(3.1415))
print(type(1 + 2j))
print(type([2, 234, 23]))
print(type({"nome": "Jhonnata"}))
print(type({12.23, 12.53}))
print(type((10, 20, 30)))